In [1]:
from pathlib import Path
import pandas as pd

In [2]:
# get the current directory
current_dir = Path.cwd()

# path to the processed data folder
processed_data_folder = current_dir.parents[1] / "data" / "processed"

In [3]:
# load the combined features dataframe
df_final = pd.read_pickle(processed_data_folder / "binding_region_combined_features_expanded.pkl")

# view the first 4 rows
print(df_final.head())

# the columns
print(df_final.columns)

  uniprot_id                            binding_region_seq  start_pos  \
0     P62258              MDDREDLVYQAKLAEQAERYDEMVESMKKVAG          0
1     P61981                                FDDAIAELDTLNED        200
2     Q15172                            QAELHPLPQLKDATSNEQ         49
3     Q15172                         LFDDLTSSYKAERQREKKKEL        428
4     Q14738  NSTPPPTQLSKIKYSGGPQIVKKERRQSSSRFNLSKNRELQKLP         60

   end_pos                                             relasa  \
0       32  [0.8867, 0.5401, 0.5562, 0.1283, 0.5467, 0.320...
1      214  [0.1491, 0.3636, 0.3476, 0.0, 0.441, 0.6942, 0...
2       67  [0.7336, 0.4545, 0.5, 0.0366, 0.588, 0.5974, 0...
3      449  [0.178, 0.0965, 0.5187, 0.492, 0.1675, 0.0982,...
4      104  [0.8021, 0.8811, 0.7055, 0.7922, 0.7078, 0.798...

                                               plddt  \
0  [0.5348, 0.8042, 0.9209, 0.9713, 0.97, 0.9722,...
1  [0.9804, 0.9806, 0.9766, 0.9707, 0.9641, 0.964...
2  [0.5446, 0.6135, 0.7935, 0.8719, 0.8925, 0.912...
3  [0.9641, 0.9639, 0.9578, 0.9658, 0.9627, 0.944...
4  [0.414, 0.3894, 0.4556, 0.4122, 0.407, 0.4423,...

                                                 sec       binding_mode  \
0  [C, C, H, H, H, H, H, H, H, H, H, H, H, H, H, ...  disorder_to_order
1         [H, H, H, H, H, H, T, G, G, G, C, C, H, H]  disorder_to_order
2  [C, C, P, P, P, P, P, P, P, G, G, G, S, C, H, ...  disorder_to_order
3  [H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, ...  disorder_to_order
4  [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, ...  disorder_to_order

      scd     shd  ...  ss_freq_G  ss_freq_H  ss_freq_I  ss_freq_P  ss_freq_S  \
0  0.0818  3.1599  ...     0.0000     0.8125        0.0     0.0000     0.0000
1  2.5240  2.4073  ...     0.2143     0.5714        0.0     0.0000     0.0000
2  0.1500  2.5888  ...     0.1667     0.2222        0.0     0.3889     0.0556
3 -0.7579  2.7998  ...     0.0000     1.0000        0.0     0.0000     0.0000
4  2.1080  3.7916  ...     0.0000     0.0000        0.0     0.1136     0.0455

   ss_freq_T  ss_freq_C  ss3_freq_H  ss3_freq_E  ss3_freq_C
0     0.0938     0.0938      0.8125         0.0      0.1875
1     0.0714     0.1429      0.7857         0.0      0.2143
2     0.0000     0.1667      0.3889         0.0      0.6111
3     0.0000     0.0000      1.0000         0.0      0.0000
4     0.0000     0.8409      0.0000         0.0      1.0000

[5 rows x 45 columns]
Index(['uniprot_id', 'binding_region_seq', 'start_pos', 'end_pos', 'relasa',
       'plddt', 'sec', 'binding_mode', 'scd', 'shd', 'fcr', 'avg_plddt',
       'avg_relasa', 'aa_freq_A', 'aa_freq_C', 'aa_freq_D', 'aa_freq_E',
       'aa_freq_F', 'aa_freq_G', 'aa_freq_H', 'aa_freq_I', 'aa_freq_K',
       'aa_freq_L', 'aa_freq_M', 'aa_freq_N', 'aa_freq_P', 'aa_freq_Q',
       'aa_freq_R', 'aa_freq_S', 'aa_freq_T', 'aa_freq_V', 'aa_freq_W',
       'aa_freq_Y', 'ss_freq_B', 'ss_freq_E', 'ss_freq_G', 'ss_freq_H',
       'ss_freq_I', 'ss_freq_P', 'ss_freq_S', 'ss_freq_T', 'ss_freq_C',
       'ss3_freq_H', 'ss3_freq_E', 'ss3_freq_C'],
      dtype='str')

In [7]:
# add length of sequence as a column
df_final["seq_length"] = df_final["binding_region_seq"].str.len()

# view the modified df
print(df_final.head())

  uniprot_id                            binding_region_seq  start_pos  \
0     P62258              MDDREDLVYQAKLAEQAERYDEMVESMKKVAG          0
1     P61981                                FDDAIAELDTLNED        200
2     Q15172                            QAELHPLPQLKDATSNEQ         49
3     Q15172                         LFDDLTSSYKAERQREKKKEL        428
4     Q14738  NSTPPPTQLSKIKYSGGPQIVKKERRQSSSRFNLSKNRELQKLP         60

   end_pos                                             relasa  \
0       32  [0.8867, 0.5401, 0.5562, 0.1283, 0.5467, 0.320...
1      214  [0.1491, 0.3636, 0.3476, 0.0, 0.441, 0.6942, 0...
2       67  [0.7336, 0.4545, 0.5, 0.0366, 0.588, 0.5974, 0...
3      449  [0.178, 0.0965, 0.5187, 0.492, 0.1675, 0.0982,...
4      104  [0.8021, 0.8811, 0.7055, 0.7922, 0.7078, 0.798...

                                               plddt  \
0  [0.5348, 0.8042, 0.9209, 0.9713, 0.97, 0.9722,...
1  [0.9804, 0.9806, 0.9766, 0.9707, 0.9641, 0.964...
2  [0.5446, 0.6135, 0.7935, 0.8719, 0.8925, 0.912...
3  [0.9641, 0.9639, 0.9578, 0.9658, 0.9627, 0.944...
4  [0.414, 0.3894, 0.4556, 0.4122, 0.407, 0.4423,...

                                                 sec       binding_mode  \
0  [C, C, H, H, H, H, H, H, H, H, H, H, H, H, H, ...  disorder_to_order
1         [H, H, H, H, H, H, T, G, G, G, C, C, H, H]  disorder_to_order
2  [C, C, P, P, P, P, P, P, P, G, G, G, S, C, H, ...  disorder_to_order
3  [H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, ...  disorder_to_order
4  [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, ...  disorder_to_order

      scd     shd  ...  ss_freq_H  ss_freq_I  ss_freq_P  ss_freq_S  ss_freq_T  \
0  0.0818  3.1599  ...     0.8125        0.0     0.0000     0.0000     0.0938
1  2.5240  2.4073  ...     0.5714        0.0     0.0000     0.0000     0.0714
2  0.1500  2.5888  ...     0.2222        0.0     0.3889     0.0556     0.0000
3 -0.7579  2.7998  ...     1.0000        0.0     0.0000     0.0000     0.0000
4  2.1080  3.7916  ...     0.0000        0.0     0.1136     0.0455     0.0000

   ss_freq_C  ss3_freq_H  ss3_freq_E  ss3_freq_C  seq_length
0     0.0938      0.8125         0.0      0.1875          32
1     0.1429      0.7857         0.0      0.2143          14
2     0.1667      0.3889         0.0      0.6111          18
3     0.0000      1.0000         0.0      0.0000          21
4     0.8409      0.0000         0.0      1.0000          44

[5 rows x 46 columns]

In [17]:
df_final.groupby(["binding_mode"]).agg(sequence_count = ('binding_region_seq', 'count'),
                                       mean_length = ('seq_length', 'mean'),
                                       sd_length = ('seq_length', 'std'),
                                       max_length = ('seq_length', 'max'),
                                       min_length = ('seq_length', 'min'))

,sequence_count,mean_length,sd_length,max_length,min_length
binding_mode,,,,,
context_dependent,77,94.129870,119.148222,843,10
disorder_to_disorder,7237,55.684538,117.234628,3421,10
disorder_to_order,4507,46.205458,112.297772,3768,10

In [14]:
df_final.groupby(["binding_mode"]).agg(mean_relasa = ('avg_relasa', 'mean'),
                                       sd_relasa = ('avg_relasa', 'std'),
                                       mean_plddt = ('avg_plddt', 'mean'),
                                       sd_plddt = ('avg_plddt', 'std'),
                                       mean_fcr = ('fcr', 'mean'),
                                       sd_fcr = ('fcr', 'std'),
                                       mean_scd = ('scd', 'mean'),
                                       sd_scd = ('scd', 'std'),
                                       mean_shd = ('shd', 'mean'),
                                       sd_shd = ('shd', 'std'))

,mean_relasa,sd_relasa,mean_plddt,sd_plddt,mean_fcr,sd_fcr,mean_scd,sd_scd,mean_shd,sd_shd
binding_mode,,,,,,,,,,
context_dependent,0.439917,0.171786,0.786955,0.182612,0.257691,0.108673,0.538908,3.046691,4.071632,1.491921
disorder_to_disorder,0.670483,0.143175,0.495672,0.156590,0.269049,0.137805,0.883084,11.216504,3.440574,1.088006
disorder_to_order,0.462680,0.158828,0.754166,0.171151,0.282177,0.128574,0.220922,1.532143,3.238308,1.116284

In [ ]:
df_final.groupby(["binding_mode"]).agg(mean_ss_H = ('ss3_freq_H', 'mean'),
                                       sd_ss_H = ('ss3_freq_H', 'std'),
                                       mean_ss_E = ('ss3_freq_E', 'mean'),
                                       sd_ss_E = ('ss3_freq_E', 'std'),
                                       mean_ss_C = ('ss3_freq_C', 'mean'),
                                       sd_ss_C = ('ss3_freq_C', 'std'))

,mean_ss_H,sd_ss_H,mean_ss_E,sd_ss_E,mean_ss_C,sd_ss_C
binding_mode,,,,,,
context_dependent,0.305195,0.282307,0.173404,0.190011,0.521406,0.258269
disorder_to_disorder,0.203712,0.259357,0.020025,0.077946,0.776263,0.264835
disorder_to_order,0.370062,0.317198,0.083609,0.157249,0.546328,0.295681

In [23]:
# 1. Define all 20 standard amino acid single-letter codes
sec_str = ["B", "E", "G", "H", "I", "P", "S", "T", "C"]

# 2. Dynamically build the aggregation dictionary
agg_dict = {}
for ss in sec_str:
    agg_dict[f'mean_ss_{ss}'] = (f'ss_freq_{ss}', 'mean')
    agg_dict[f'sd_ss_{ss}'] = (f'ss_freq_{ss}', 'std')

# 3. Pass the dictionary unpacker (**) into the .agg() method
df_final.groupby(["binding_mode"]).agg(**agg_dict)

,mean_ss_B,sd_ss_B,mean_ss_E,sd_ss_E,mean_ss_G,sd_ss_G,mean_ss_H,sd_ss_H,mean_ss_I,sd_ss_I,mean_ss_P,sd_ss_P,mean_ss_S,sd_ss_S,mean_ss_T,sd_ss_T,mean_ss_C,sd_ss_C
binding_mode,,,,,,,,,,,,,,,,,,
context_dependent,0.006809,0.014908,0.166594,0.188235,0.041922,0.065296,0.258400,0.287434,0.004873,0.019960,0.053731,0.106672,0.073042,0.070463,0.107514,0.077801,0.287116,0.240231
disorder_to_disorder,0.002262,0.013648,0.017763,0.076019,0.025868,0.068780,0.177304,0.254927,0.000539,0.009400,0.064755,0.112730,0.063831,0.079910,0.073846,0.097434,0.573827,0.294761
disorder_to_order,0.008157,0.025571,0.075453,0.154869,0.044261,0.091855,0.323064,0.322559,0.002736,0.024487,0.056803,0.108251,0.089135,0.091909,0.121317,0.114624,0.279067,0.235731

In [21]:
# 1. Define all 20 standard amino acid single-letter codes
amino_acids = ["A", "C", "D", "E", "F", "G", "H", "I", "K", "L", 
               "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y"]

# 2. Dynamically build the aggregation dictionary
agg_dict = {}
for aa in amino_acids:
    agg_dict[f'mean_aa_{aa}'] = (f'aa_freq_{aa}', 'mean')
    agg_dict[f'sd_aa_{aa}'] = (f'aa_freq_{aa}', 'std')

# 3. Pass the dictionary unpacker (**) into the .agg() method
df_final.groupby(["binding_mode"]).agg(**agg_dict)

,mean_aa_A,sd_aa_A,mean_aa_C,sd_aa_C,mean_aa_D,sd_aa_D,mean_aa_E,sd_aa_E,mean_aa_F,sd_aa_F,...,mean_aa_S,sd_aa_S,mean_aa_T,sd_aa_T,mean_aa_V,sd_aa_V,mean_aa_W,sd_aa_W,mean_aa_Y,sd_aa_Y
binding_mode,,,,,,,,,,,,,,,,,,,,,
context_dependent,0.056730,0.050896,0.026148,0.040199,0.073406,0.069336,0.072087,0.055468,0.034191,0.029960,...,0.069151,0.046998,0.050940,0.037250,0.054258,0.047041,0.013694,0.022800,0.029101,0.036685
disorder_to_disorder,0.082056,0.074297,0.013796,0.028290,0.056231,0.059612,0.087608,0.081208,0.021036,0.032511,...,0.103060,0.077947,0.055937,0.054221,0.045183,0.045954,0.007431,0.019108,0.013710,0.026571
disorder_to_order,0.068562,0.067536,0.017117,0.034906,0.058606,0.060231,0.082921,0.077336,0.032505,0.042815,...,0.073755,0.067849,0.051887,0.054557,0.052982,0.052782,0.010271,0.023816,0.026421,0.039161