In [2]:
from process_mobidb_scores import get_mobidb_scores
from alphasync_data import get_alphasync_data, parse_alphasync_data
from protein_region_features import features_binding_region_df, get_amino_acid_composition, calculate_scd, calculate_shd, calculate_fcr, get_sec_str_freq, get_average_feature_value
from pathlib import Path
import pandas as pd
import numpy as np

In [3]:
# get the current directory
current_dir = Path.cwd()

# path to the input fasta file
input_fasta = current_dir.parents[1] / "data" / "raw" / "mobidb_search_2026-05-05T08-28-46.fasta"

# path to the processed data folder
processed_data_folder = current_dir.parents[1] / "data" / "processed"

# define the output data folder for the alphasync data
output_data_folder = current_dir.parents[1] / "data" / "raw" / "alphasync_data"

In [4]:
# get the mobidb scores for the given input fasta file and the given score patterns
human_proteome_seq_df = get_mobidb_scores(str(input_fasta), ["derived-binding_mode_disorder_to_disorder-mobi", "derived-binding_mode_disorder_to_order-mobi", "derived-binding_mode_context_dependent-mobi"])

# print the first 5 rows of the complete data dataframe
print(human_proteome_seq_df.head())

# print the number of rows in the complete data dataframe
print(f"Number of rows in the complete data dataframe: {human_proteome_seq_df.shape[0]}")

  uniprot_id                                           sequence  \
0     P31946  MTMDKSELVQKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLL...
1     Q04917  MGDREQLLQRARLAEQAERYDDMASAMKAVTELNEPLSNEDRNLLS...
2     P62258  MDDREDLVYQAKLAEQAERYDEMVESMKKVAGMDVELTVEERNLLS...
3     P61981  MVDREQLVQKARLAEQAERYDDMAAAMKNVTELNEPLSNEERNLLS...
4     P31947  MERASLIQKAKLAEQAERYEDMAAFMKGAVEKGEELSCEERNLLSV...

      derived_binding_mode_disorder_to_disorder_mobi  \
0                                                NaN
1  0000000000000000000000000000000000000000000000...
2  0000000000000000000000000000000000000000000000...
3                                                NaN
4  0000000000000000000000000000000000000000000000...

         derived_binding_mode_disorder_to_order_mobi  \
0                                                NaN
1                                                NaN
2  1111111111111111111111111111111100000000000000...
3  0000000000000000000000000000000000000000000000...
4                                                NaN

  derived_binding_mode_context_dependent_mobi
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
Number of rows in the complete data dataframe: 82518

In [5]:
# filter the dataframe to get only those that has mobidb scores for at least one of the binding mode scores
binding_mode_scores = ["derived_binding_mode_disorder_to_disorder_mobi", "derived_binding_mode_disorder_to_order_mobi", "derived_binding_mode_context_dependent_mobi"]
df_binding_idr_seq = human_proteome_seq_df.dropna(subset=binding_mode_scores, how="all").copy()

# print the number of rows in the filtered dataframe
print(f"Number of rows in the filtered dataframe: {df_binding_idr_seq.shape[0]}")

print(df_binding_idr_seq.head())

Number of rows in the filtered dataframe: 4751
  uniprot_id                                           sequence  \
1     Q04917  MGDREQLLQRARLAEQAERYDDMASAMKAVTELNEPLSNEDRNLLS...
2     P62258  MDDREDLVYQAKLAEQAERYDEMVESMKKVAGMDVELTVEERNLLS...
3     P61981  MVDREQLVQKARLAEQAERYDDMAAAMKNVTELNEPLSNEERNLLS...
4     P31947  MERASLIQKAKLAEQAERYEDMAAFMKGAVEKGEELSCEERNLLSV...
5     P27348  MEKTELIQKAKLAEQAERYDDMATCMKAVTEQGAELSNEERNLLSV...

      derived_binding_mode_disorder_to_disorder_mobi  \
1  0000000000000000000000000000000000000000000000...
2  0000000000000000000000000000000000000000000000...
3                                                NaN
4  0000000000000000000000000000000000000000000000...
5  0000000000000000000000000000000000000000000000...

         derived_binding_mode_disorder_to_order_mobi  \
1                                                NaN
2  1111111111111111111111111111111100000000000000...
3  0000000000000000000000000000000000000000000000...
4                                                NaN
5                                                NaN

  derived_binding_mode_context_dependent_mobi
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN

In [9]:
# save the dataframe as csv files in the processed data folder
df_binding_idr_seq.to_csv(processed_data_folder / "binding_idr_sequences.csv", index=False)

In [6]:
# get the alphasync data for the binding idr sequences
print("Downloading the alphasync data for the given uniprot IDs...")
get_alphasync_data(df_binding_idr_seq["uniprot_id"].tolist(), str(output_data_folder))

Downloading the alphasync data for the given uniprot IDs...
Failed to download A0A0A0MSA1 (Status: 404)
Failed to download F2Z2U4 (Status: 404)
Failed to download A0A8V8TRG9 (Status: 404)
Failed to download E9PG32 (Status: 404)
Failed to download A0A669KB38 (Status: 404)

In [6]:
# remove the ids that couldn't be downloaded from the alphasync data and save the filtered dataframe as a csv file in the processed data folder
remove_ids = ["A0A0A0MSA1", "F2Z2U4", "E9PG32", "A0A8V8TRG9", "A0A669KB38"]

# filter the dataframe to remove the rows with the uniprot ids in the remove_ids list
df_binding_idr_seq_filtered = df_binding_idr_seq[~df_binding_idr_seq["uniprot_id"].isin(remove_ids)].copy()
#df_binding_idr_seq_filtered.to_csv(processed_data_folder / "binding_idr_sequences_filtered.csv", index=False)

In [ ]:
# read the filtered dataframe from the csv file in the processed data folder
#df_binding_idr_seq_filtered = pd.read_csv(processed_data_folder / "binding_idr_sequences_filtered.csv")

In [7]:
# add the alphasync data for the filtered dataframe
df_binding_idr_seq_filtered["plddt"] = df_binding_idr_seq_filtered["uniprot_id"].apply(lambda x: parse_alphasync_data(x, "plddt", str(output_data_folder), divide_by_100=True))
df_binding_idr_seq_filtered["relasa"] = df_binding_idr_seq_filtered["uniprot_id"].apply(lambda x: parse_alphasync_data(x, "relasa", str(output_data_folder)))
df_binding_idr_seq_filtered["sec"] = df_binding_idr_seq_filtered["uniprot_id"].apply(lambda x: parse_alphasync_data(x, "sec", str(output_data_folder)))

print(df_binding_idr_seq_filtered.head())

# save the updated dataframe as csv and pickle files in the processed data folder
#df_binding_idr_seq_filtered.to_csv(processed_data_folder / "binding_idr_sequences_filtered_with_alphasync.csv", index=False)
df_binding_idr_seq_filtered.to_pickle(processed_data_folder / "binding_idr_sequences_filtered_with_alphasync.pkl")

  uniprot_id                                           sequence  \
1     Q04917  MGDREQLLQRARLAEQAERYDDMASAMKAVTELNEPLSNEDRNLLS...
2     P62258  MDDREDLVYQAKLAEQAERYDEMVESMKKVAGMDVELTVEERNLLS...
3     P61981  MVDREQLVQKARLAEQAERYDDMAAAMKNVTELNEPLSNEERNLLS...
4     P31947  MERASLIQKAKLAEQAERYEDMAAFMKGAVEKGEELSCEERNLLSV...
5     P27348  MEKTELIQKAKLAEQAERYDDMATCMKAVTEQGAELSNEERNLLSV...

      derived_binding_mode_disorder_to_disorder_mobi  \
1  0000000000000000000000000000000000000000000000...
2  0000000000000000000000000000000000000000000000...
3                                                NaN
4  0000000000000000000000000000000000000000000000...
5  0000000000000000000000000000000000000000000000...

         derived_binding_mode_disorder_to_order_mobi  \
1                                                NaN
2  1111111111111111111111111111111100000000000000...
3  0000000000000000000000000000000000000000000000...
4                                                NaN
5                                                NaN

  derived_binding_mode_context_dependent_mobi  \
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN

                                               plddt  \
1  [0.5519, 0.7636, 0.8977, 0.954, 0.961, 0.9647,...
2  [0.5348, 0.8042, 0.9209, 0.9713, 0.97, 0.9722,...
3  [0.545, 0.7109, 0.884, 0.9515, 0.9529, 0.9604,...
4  [0.7299, 0.9104, 0.9382, 0.948, 0.9708, 0.9791...
5  [0.7066, 0.9087, 0.9528, 0.9633, 0.9736, 0.981...

                                              relasa  \
1  [0.8473, 0.5464, 0.5508, 0.1547, 0.4206, 0.481...
2  [0.8867, 0.5401, 0.5562, 0.1283, 0.5467, 0.320...
3  [1.1921, 0.5879, 0.3422, 0.1509, 0.6682, 0.574...
4  [0.5517, 0.7103, 0.0943, 0.6198, 0.3357, 0.078...
5  [0.6256, 0.6495, 0.2304, 0.5583, 0.4206, 0.073...

                                                 sec
1  [C, C, H, H, H, H, H, H, H, H, H, H, H, H, H, ...
2  [C, C, H, H, H, H, H, H, H, H, H, H, H, H, H, ...
3  [C, C, C, H, H, H, H, H, H, H, H, H, H, H, H, ...
4  [C, C, H, H, H, H, H, H, H, H, H, H, H, H, H, ...
5  [C, C, H, H, H, H, H, H, H, H, H, H, H, H, H, ...

In [8]:
# load the binding region dataframes from the pickle files in the processed data folder
df_binding_idr_seq_filtered = pd.read_pickle(processed_data_folder / "binding_idr_sequences_filtered_with_alphasync.pkl")

In [9]:

# get features for the binding regions from that of the complete protein sequence
df_binding_region_do = features_binding_region_df(df_binding_idr_seq_filtered, "derived_binding_mode_disorder_to_order_mobi", {"plddt", "relasa", "sec"})
df_binding_region_do["binding_mode"] = "disorder_to_order"
print(df_binding_region_do.head())
df_binding_region_dd = features_binding_region_df(df_binding_idr_seq_filtered, "derived_binding_mode_disorder_to_disorder_mobi", {"plddt", "relasa", "sec"})
df_binding_region_dd["binding_mode"] = "disorder_to_disorder"
print(df_binding_region_dd.head())
df_binding_region_cd = features_binding_region_df(df_binding_idr_seq_filtered, "derived_binding_mode_context_dependent_mobi", {"plddt", "relasa", "sec"})
df_binding_region_cd["binding_mode"] = "context_dependent"
print(df_binding_region_cd.head())


# save the dataframes as csv files and pickle files in the processed data folder
df_binding_region_do.to_csv(processed_data_folder / "binding_region_disorder_to_order.csv", index=False)
df_binding_region_do.to_pickle(processed_data_folder / "binding_region_disorder_to_order.pkl")
df_binding_region_dd.to_csv(processed_data_folder / "binding_region_disorder_to_disorder.csv", index=False)
df_binding_region_dd.to_pickle(processed_data_folder / "binding_region_disorder_to_disorder.pkl")
df_binding_region_cd.to_csv(processed_data_folder / "binding_region_context_dependent.csv", index=False)
df_binding_region_cd.to_pickle(processed_data_folder / "binding_region_context_dependent.pkl")

  uniprot_id                            binding_region_seq  start_pos  \
0     P62258              MDDREDLVYQAKLAEQAERYDEMVESMKKVAG          0
1     P61981                                FDDAIAELDTLNED        200
2     Q15172                            QAELHPLPQLKDATSNEQ         49
3     Q15172                         LFDDLTSSYKAERQREKKKEL        428
4     Q14738  NSTPPPTQLSKIKYSGGPQIVKKERRQSSSRFNLSKNRELQKLP         60

   end_pos                                                sec  \
0       32  [C, C, H, H, H, H, H, H, H, H, H, H, H, H, H, ...
1      214         [H, H, H, H, H, H, T, G, G, G, C, C, H, H]
2       67  [C, C, P, P, P, P, P, P, P, G, G, G, S, C, H, ...
3      449  [H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, ...
4      104  [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, ...

                                              relasa  \
0  [0.8867, 0.5401, 0.5562, 0.1283, 0.5467, 0.320...
1  [0.1491, 0.3636, 0.3476, 0.0, 0.441, 0.6942, 0...
2  [0.7336, 0.4545, 0.5, 0.0366, 0.588, 0.5974, 0...
3  [0.178, 0.0965, 0.5187, 0.492, 0.1675, 0.0982,...
4  [0.8021, 0.8811, 0.7055, 0.7922, 0.7078, 0.798...

                                               plddt       binding_mode
0  [0.5348, 0.8042, 0.9209, 0.9713, 0.97, 0.9722,...  disorder_to_order
1  [0.9804, 0.9806, 0.9766, 0.9707, 0.9641, 0.964...  disorder_to_order
2  [0.5446, 0.6135, 0.7935, 0.8719, 0.8925, 0.912...  disorder_to_order
3  [0.9641, 0.9639, 0.9578, 0.9658, 0.9627, 0.944...  disorder_to_order
4  [0.414, 0.3894, 0.4556, 0.4122, 0.407, 0.4423,...  disorder_to_order
  uniprot_id    binding_region_seq  start_pos  end_pos  \
0     Q04917            QQDEEAGEGN        236      246
1     P62258  QGDGEEQNKEALQDVEDENQ        235      255
2     P31947       NAGEEGGEAPQEPQS        233      248
3     P27348        SAGEECDAAEGAEN        231      245
4     P63104         QGDEAEAGEGGEN        232      245

                                                 sec  \
0                     [H, H, H, H, H, H, H, T, T, C]
1  [H, T, C, C, C, C, C, C, C, P, P, P, C, C, C, ...
2      [H, H, H, H, H, T, C, C, C, C, C, P, P, P, C]
3         [H, H, H, H, H, H, H, H, H, H, T, T, C, C]
4            [H, H, H, H, H, H, H, H, T, T, C, C, C]

                                              relasa  \
0  [0.2243, 0.6028, 0.6364, 0.6075, 0.7009, 0.553...
1  [0.6122, 0.6495, 0.6791, 0.3608, 0.7056, 0.939...
2  [0.1925, 0.5289, 0.5979, 0.7664, 0.8131, 0.639...
3  [0.2797, 0.4298, 0.3608, 0.6589, 0.6869, 0.554...
4  [0.6262, 0.4021, 0.6417, 0.6589, 0.4959, 0.803...

                                               plddt          binding_mode
0  [0.7981, 0.7741, 0.764, 0.7367, 0.7182, 0.6849...  disorder_to_disorder
1  [0.8046, 0.6758, 0.6028, 0.4909, 0.4414, 0.426...  disorder_to_disorder
2  [0.8007, 0.7783, 0.6656, 0.5777, 0.5106, 0.435...  disorder_to_disorder
3  [0.6961, 0.6413, 0.5651, 0.5439, 0.4969, 0.446...  disorder_to_disorder
4  [0.6225, 0.568, 0.5329, 0.4894, 0.474, 0.4206,...  disorder_to_disorder
  uniprot_id                                 binding_region_seq  start_pos  \
0     Q96AP0  SGRLVLRPWIRELILGSETPSSPRAGQLLEVLQDAEAAVAGPSHAP...          3
1     P07550                                FLLAPNGSHAPDHDVTQER          9
2     P10109                   QICLTKSMDNMTVRVPETVADARQSIDVGKTS        152
3     P58335  RRAFDLYFVLDKSGSVANNWIEIYNFVQQLAERFVSPEMRLSFIVF...         39
4     P35414                                      ECEYTDWKSSGAL         17

   end_pos                                                sec  \
0      155  [C, C, C, C, P, P, P, P, C, H, H, H, H, H, H, ...
1       28  [C, C, C, P, P, P, C, C, C, C, C, S, H, H, H, ...
2      184  [G, C, B, C, C, G, G, G, T, T, E, E, E, E, C, ...
3      217  [C, C, C, E, E, E, E, E, E, E, E, C, S, G, G, ...
4       30            [C, C, C, C, C, C, C, C, C, C, C, T, H]

                                              relasa  \
0  [0.951, 0.6392, 0.7887, 0.623, 0.7515, 0.1571,...
1  [0.8421, 0.8848, 0.8115, 0.8017, 0.8247, 0.903...
2  [0.3458, 0.0359, 0.4595, 0.0105, 0.3313, 0.595...
3  [0.8642, 0.2226, 0.438, 0.0219, 0.0214, 0.0, 0...
4  [0.9019, 0.2635, 0.8318, 0.4784, 0.5092, 0.315...

                                               plddt       binding_mode
0  [0.5025, 0.5284, 0.6686, 0.64, 0.7823, 0.8008,...  context_dependent
1  [0.4525, 0.4054, 0.487, 0.4582, 0.5103, 0.4315...  context_dependent
2  [0.9789, 0.9808, 0.9725, 0.9737, 0.959, 0.9421...  context_dependent
3  [0.466, 0.5827, 0.7075, 0.8062, 0.8963, 0.9171...  context_dependent
4  [0.6472, 0.7339, 0.7871, 0.7748, 0.7826, 0.759...  context_dependent

In [4]:
# read the dataframes from the pickle files in the processed data folder
df_binding_region_do = pd.read_pickle(processed_data_folder / "binding_region_disorder_to_order.pkl")
df_binding_region_dd = pd.read_pickle(processed_data_folder / "binding_region_disorder_to_disorder.pkl")
df_binding_region_cd = pd.read_pickle(processed_data_folder / "binding_region_context_dependent.pkl")

# combine the three dataframes into one dataframe
df_binding_region_combined = pd.concat([df_binding_region_do, df_binding_region_dd, df_binding_region_cd], ignore_index=True)

In [5]:
# filter the dataframe to remove rows where the plddt column is empty or not a list
is_not_empty = df_binding_region_combined["plddt"].apply(lambda x: isinstance(x, list) and len(x) > 0)
df_binding_region_combined = df_binding_region_combined[is_not_empty]

In [ ]:
#df_binding_region_combined["amino_acid_composition"] = df_binding_region_combined["binding_region_seq"].apply(get_amino_acid_composition)

#df_expanded = pd.DataFrame(df_binding_region_combined["amino_acid_composition"].tolist(), index=df_binding_region_combined.index).add_prefix("aa_freq_")
#df_expanded

,aa_freq_A,aa_freq_C,aa_freq_D,aa_freq_E,aa_freq_F,aa_freq_G,aa_freq_H,aa_freq_I,aa_freq_K,aa_freq_L,aa_freq_M,aa_freq_N,aa_freq_P,aa_freq_Q,aa_freq_R,aa_freq_S,aa_freq_T,aa_freq_V,aa_freq_W,aa_freq_Y
0,0.1250,0.0000,0.1250,0.1562,0.0000,0.0312,0.0000,0.0000,0.0938,0.0625,0.0938,0.0000,0.0000,0.0625,0.0625,0.0312,0.0000,0.0938,0.0000,0.0625
1,0.1429,0.0000,0.2857,0.1429,0.0714,0.0000,0.0000,0.0714,0.0000,0.1429,0.0000,0.0714,0.0000,0.0000,0.0000,0.0000,0.0714,0.0000,0.0000,0.0000
2,0.1111,0.0000,0.0556,0.1111,0.0000,0.0000,0.0556,0.0000,0.0556,0.1667,0.0000,0.0556,0.1111,0.1667,0.0000,0.0556,0.0556,0.0000,0.0000,0.0000
3,0.0476,0.0000,0.0952,0.1429,0.0476,0.0000,0.0000,0.0000,0.1905,0.1429,0.0000,0.0000,0.0000,0.0476,0.0952,0.0952,0.0476,0.0000,0.0000,0.0476
4,0.0000,0.0000,0.0000,0.0455,0.0227,0.0455,0.0000,0.0455,0.1364,0.0909,0.0000,0.0682,0.1136,0.0909,0.0909,0.1591,0.0455,0.0227,0.0000,0.0227
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11824,0.0556,0.0000,0.0556,0.0556,0.0000,0.0278,0.0278,0.0833,0.0556,0.0556,0.0000,0.0556,0.0556,0.0556,0.0278,0.1111,0.0278,0.1944,0.0278,0.0278
11825,0.0000,0.1786,0.1071,0.1071,0.0357,0.0714,0.0357,0.0357,0.0714,0.0000,0.0000,0.1071,0.0000,0.0714,0.0357,0.0714,0.0357,0.0000,0.0357,0.0000
11826,0.0870,0.0145,0.0580,0.1014,0.0290,0.0145,0.0000,0.0725,0.0725,0.1159,0.0580,0.0000,0.0725,0.0725,0.0435,0.1014,0.0435,0.0290,0.0000,0.0145
11827,0.0000,0.0000,0.2000,0.0000,0.0000,0.0000,0.1000,0.1000,0.1000,0.1000,0.0000,0.0000,0.0000,0.1000,0.0000,0.1000,0.0000,0.2000,0.0000,0.0000
11828,0.0870,0.0145,0.0652,0.0797,0.0290,0.0725,0.0471,0.0145,0.0362,0.0616,0.0181,0.0072,0.0435,0.0616,0.0833,0.0507,0.0833,0.0580,0.0362,0.0507

In [ ]:
# add the features for the binding regions to the combined dataframe
df_binding_region_combined["amino_acid_composition"] = df_binding_region_combined["binding_region_seq"].apply(get_amino_acid_composition)
df_binding_region_combined["scd"] = df_binding_region_combined["binding_region_seq"].apply(lambda x: calculate_scd(x, need_rounding=True, round_to=4))
df_binding_region_combined["shd"] = df_binding_region_combined["binding_region_seq"].apply(lambda x: calculate_shd(x, need_rounding=True, round_to=4))
df_binding_region_combined["fcr"] = df_binding_region_combined["binding_region_seq"].apply(lambda x: calculate_fcr(x, need_rounding=True, round_to=4))
df_binding_region_combined["sec_str_freq"] = df_binding_region_combined["sec"].apply(get_sec_str_freq)
df_binding_region_combined["sec_str3_freq"] = df_binding_region_combined["sec"].apply(lambda x: get_sec_str_freq(x, convert_3_state=True))
df_binding_region_combined["avg_plddt"] = df_binding_region_combined["plddt"].map(np.mean).round(4)
df_binding_region_combined["avg_relasa"] = df_binding_region_combined["relasa"].map(np.mean).round(4)

# print the first 5 rows of the combined dataframe with features
print(df_binding_region_combined.head())

# save the combined dataframe with features as a csv file in the processed data folder
df_binding_region_combined.to_csv(processed_data_folder / "binding_region_combined_features.csv", index=False)

# save the combined dataframe with features as a pickle file in the processed data folder
#df_binding_region_combined.to_pickle(processed_data_folder / "binding_region_combined_features.pkl")

  uniprot_id                            binding_region_seq  start_pos  \
0     P62258              MDDREDLVYQAKLAEQAERYDEMVESMKKVAG          0
1     P61981                                FDDAIAELDTLNED        200
2     Q15172                            QAELHPLPQLKDATSNEQ         49
3     Q15172                         LFDDLTSSYKAERQREKKKEL        428
4     Q14738  NSTPPPTQLSKIKYSGGPQIVKKERRQSSSRFNLSKNRELQKLP         60

   end_pos                                                sec  \
0       32  [C, C, H, H, H, H, H, H, H, H, H, H, H, H, H, ...
1      214         [H, H, H, H, H, H, T, G, G, G, C, C, H, H]
2       67  [C, C, P, P, P, P, P, P, P, G, G, G, S, C, H, ...
3      449  [H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, ...
4      104  [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, ...

                                              relasa  \
0  [0.8867, 0.5401, 0.5562, 0.1283, 0.5467, 0.320...
1  [0.1491, 0.3636, 0.3476, 0.0, 0.441, 0.6942, 0...
2  [0.7336, 0.4545, 0.5, 0.0366, 0.588, 0.5974, 0...
3  [0.178, 0.0965, 0.5187, 0.492, 0.1675, 0.0982,...
4  [0.8021, 0.8811, 0.7055, 0.7922, 0.7078, 0.798...

                                               plddt       binding_mode  \
0  [0.5348, 0.8042, 0.9209, 0.9713, 0.97, 0.9722,...  disorder_to_order
1  [0.9804, 0.9806, 0.9766, 0.9707, 0.9641, 0.964...  disorder_to_order
2  [0.5446, 0.6135, 0.7935, 0.8719, 0.8925, 0.912...  disorder_to_order
3  [0.9641, 0.9639, 0.9578, 0.9658, 0.9627, 0.944...  disorder_to_order
4  [0.414, 0.3894, 0.4556, 0.4122, 0.407, 0.4423,...  disorder_to_order

                              amino_acid_composition     scd     shd     fcr  \
0  {'A': 0.125, 'C': 0.0, 'D': 0.125, 'E': 0.1562...  0.0818  3.1599  0.4375
1  {'A': 0.1429, 'C': 0.0, 'D': 0.2857, 'E': 0.14...  2.5240  2.4073  0.4286
2  {'A': 0.1111, 'C': 0.0, 'D': 0.0556, 'E': 0.11...  0.1500  2.5888  0.2222
3  {'A': 0.0476, 'C': 0.0, 'D': 0.0952, 'E': 0.14... -0.7579  2.7998  0.5238
4  {'A': 0.0, 'C': 0.0, 'D': 0.0, 'E': 0.0455, 'F...  2.1080  3.7916  0.2727

                                        sec_str_freq  \
0  {'B': 0.0, 'E': 0.0, 'G': 0.0, 'H': 0.8125, 'I...
1  {'B': 0.0, 'E': 0.0, 'G': 0.2143, 'H': 0.5714,...
2  {'B': 0.0, 'E': 0.0, 'G': 0.1667, 'H': 0.2222,...
3  {'B': 0.0, 'E': 0.0, 'G': 0.0, 'H': 1.0, 'I': ...
4  {'B': 0.0, 'E': 0.0, 'G': 0.0, 'H': 0.0, 'I': ...

                          sec_str3_freq  avg_plddt  avg_relasa
0  {'H': 0.8125, 'E': 0.0, 'C': 0.1875}     0.9583      0.3256
1  {'H': 0.7857, 'E': 0.0, 'C': 0.2143}     0.9265      0.4517
2  {'H': 0.3889, 'E': 0.0, 'C': 0.6111}     0.8542      0.4604
3        {'H': 1.0, 'E': 0.0, 'C': 0.0}     0.9376      0.4214
4        {'H': 0.0, 'E': 0.0, 'C': 1.0}     0.5394      0.6497

In [ ]:
# expand the features
df_aa = pd.DataFrame(df_binding_region_combined["amino_acid_composition"].tolist(), index=df_binding_region_combined.index).add_prefix("aa_freq_")
df_ss = pd.DataFrame(df_binding_region_combined["sec_str_freq"].tolist(), index=df_binding_region_combined.index).add_prefix("ss_freq_")
df_ss3 = pd.DataFrame(df_binding_region_combined["sec_str3_freq"].tolist(), index=df_binding_region_combined.index).add_prefix("ss3_freq_")
df_final = pd.concat([df_binding_region_combined.drop(columns=["amino_acid_composition", "sec_str_freq", "sec_str3_freq"]), df_aa, df_ss, df_ss3], axis=1)

print(df_final.head())

# save the final dataframe with expanded features as a pickle file in the processed data folder
df_final.to_pickle(processed_data_folder / "binding_region_combined_features_expanded.pkl")

  uniprot_id                            binding_region_seq  start_pos  \
0     P62258              MDDREDLVYQAKLAEQAERYDEMVESMKKVAG          0
1     P61981                                FDDAIAELDTLNED        200
2     Q15172                            QAELHPLPQLKDATSNEQ         49
3     Q15172                         LFDDLTSSYKAERQREKKKEL        428
4     Q14738  NSTPPPTQLSKIKYSGGPQIVKKERRQSSSRFNLSKNRELQKLP         60

   end_pos                                                sec  \
0       32  [C, C, H, H, H, H, H, H, H, H, H, H, H, H, H, ...
1      214         [H, H, H, H, H, H, T, G, G, G, C, C, H, H]
2       67  [C, C, P, P, P, P, P, P, P, G, G, G, S, C, H, ...
3      449  [H, H, H, H, H, H, H, H, H, H, H, H, H, H, H, ...
4      104  [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, ...

                                              relasa  \
0  [0.8867, 0.5401, 0.5562, 0.1283, 0.5467, 0.320...
1  [0.1491, 0.3636, 0.3476, 0.0, 0.441, 0.6942, 0...
2  [0.7336, 0.4545, 0.5, 0.0366, 0.588, 0.5974, 0...
3  [0.178, 0.0965, 0.5187, 0.492, 0.1675, 0.0982,...
4  [0.8021, 0.8811, 0.7055, 0.7922, 0.7078, 0.798...

                                               plddt       binding_mode  \
0  [0.5348, 0.8042, 0.9209, 0.9713, 0.97, 0.9722,...  disorder_to_order
1  [0.9804, 0.9806, 0.9766, 0.9707, 0.9641, 0.964...  disorder_to_order
2  [0.5446, 0.6135, 0.7935, 0.8719, 0.8925, 0.912...  disorder_to_order
3  [0.9641, 0.9639, 0.9578, 0.9658, 0.9627, 0.944...  disorder_to_order
4  [0.414, 0.3894, 0.4556, 0.4122, 0.407, 0.4423,...  disorder_to_order

      scd     shd  ...  ss_freq_G  ss_freq_H  ss_freq_I  ss_freq_P  ss_freq_S  \
0  0.0818  3.1599  ...     0.0000     0.8125        0.0     0.0000     0.0000
1  2.5240  2.4073  ...     0.2143     0.5714        0.0     0.0000     0.0000
2  0.1500  2.5888  ...     0.1667     0.2222        0.0     0.3889     0.0556
3 -0.7579  2.7998  ...     0.0000     1.0000        0.0     0.0000     0.0000
4  2.1080  3.7916  ...     0.0000     0.0000        0.0     0.1136     0.0455

   ss_freq_T  ss_freq_C  ss3_freq_H  ss3_freq_E  ss3_freq_C
0     0.0938     0.0938      0.8125         0.0      0.1875
1     0.0714     0.1429      0.7857         0.0      0.2143
2     0.0000     0.1667      0.3889         0.0      0.6111
3     0.0000     0.0000      1.0000         0.0      0.0000
4     0.0000     0.8409      0.0000         0.0      1.0000

[5 rows x 45 columns]

In [ ]:
#df_dd_do_seq["id_col"] = df_dd_do_seq["uniprot_id"] + "_" + df_dd_do_seq["start_pos"] + "_" + df_dd_do_seq["end_pos"]
#df_dd_do_seq

,uniprot_id,binding_region_seq,start_pos,end_pos,label,id_col
0,Q04917,QQDEEAGEGN,236,246,disorder_to_disorder,Q04917_236_246
1,P62258,QGDGEEQNKEALQDVEDENQ,235,255,disorder_to_disorder,P62258_235_255
2,P31947,NAGEEGGEAPQEPQS,233,248,disorder_to_disorder,P31947_233_248
3,P27348,SAGEECDAAEGAEN,231,245,disorder_to_disorder,P27348_231_245
4,P63104,QGDEAEAGEGGEN,232,245,disorder_to_disorder,P63104_232_245
...,...,...,...,...,...,...
11765,A0A0A0MTJ0,NQKKIRGILESLMCNESS,287,305,disorder_to_order,A0A0A0MTJ0_287_305
11766,A0A0A0MTJ0,ETLQAFDSHYDYTICGDSED,375,395,disorder_to_order,A0A0A0MTJ0_375_395
11767,U3KQA6,EQELVVTIPKN,183,194,disorder_to_order,U3KQA6_183_194
11768,A0A140T913,MTHHAVSDHEATL,212,225,disorder_to_order,A0A140T913_212_225
11769,A0A087X2I1,MADPRDKALQDYRK,14,28,disorder_to_order,A0A087X2I1_14_28

In [ ]:
#from df_to_fasta import dataframe_to_fasta
#dataframe_to_fasta(df_dd_do_seq, "id_col", "binding_region_seq", "disorder_to_disorder_and_disorder_to_order_sequences.fasta")
# filter same sequences
#df_dd_do_seq.drop_duplicates(subset=["binding_region_seq"], inplace=True)
#print(f"Number of unique sequences in disorder to disorder and disorder to order binding mode classes: {len(df_dd_do_seq)}")

Number of unique sequences in disorder to disorder and disorder to order binding mode classes: 11762